version: 2.0.{build}

image: Visual Studio 2015

nuget:
  account_feed: true
  project_feed: true

configuration: Release

build:
  parallel: true
  verbosity: minimal

cache:
  - Source\packages -> Source\**\packages.config

before_build:
  - ps: if (!(Get-Variable -Name env:APPVEYOR_REPO_TAG -ErrorAction SilentlyContinue)) { $env:APPVEYOR_REPO_TAG = "2.0.0" }
  - ps: $env:APPVEYOR_REPO_TAG = $env:APPVEYOR_REPO_TAG -replace 'v',''
  - ps: Write-Host "Setting version to '$APPVEYOR_REPO_TAG'"
  - ps: (Get-Content Source\Anaximander\Properties\AssemblyInfo.cs) -replace '1\.0\.\*', "$env:APPVEYOR_REPO_TAG.*" | Set-Content Source\Anaximander\Properties\AssemblyInfo.cs
  - ps: (Get-Content Source\RollbarCrashReporter\Properties\AssemblyInfo.cs) -replace '1\.0\.\*', "$env:APPVEYOR_REPO_TAG.*" | Set-Content Source\RollbarCrashReporter\Properties\AssemblyInfo.cs
  - ps: (Get-Content Source\Anaximander\app.config) -replace 'COMPILED_BY = "?mono?"', 'COMPILED_BY = "VS2015"' | Set-Content Source\Anaximander\app.config
  - ps: (Get-Content Source\RollbarCrashReporter\app.config) -replace 'COMPILED_BY = "?mono?"', 'COMPILED_BY = "VS2015"' | Set-Content Source\RollbarCrashReporter\app.config
  - nuget restore Source\Anaximander.sln

after_build:
  - ps: (Get-Content bin\Anaximander.exe.config) -replace 'param name="Environment" value="development"', 'param name="Environment" value="production"' | Set-Content bin\Anaximander.exe.config
  - ps: (Get-Content bin\RollbarCrashReporter.exe.config) -replace 'param name="Environment" value="development"', 'param name="Environment" value="production"' | Set-Content bin\RollbarCrashReporter.exe.config
  - rename bin Anaximander2

artifacts:
  - path: Anaximander2
    name: anaximander2-dotnet
    type: Zip

deploy:
  provider: GitHub
  auth_token:
    secure: "QUqhwTOVl7qBikVjSddIdfQ/mJAYlmSwsPPxTW8kSPJKALifV/E3UFycqJyf6USR"
  artifact: anaximander2-dotnet
  draft: true
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
