version: 2.0.{build}

image: Visual Studio 2015

nuget:
  account_feed: true
  project_feed: true

configuration: Release

build:
  parallel: true
  verbosity: minimal

before_build:
  - ps: (Get-Content Anaximander2\Anaximander.exe.config) -replace 'ANAX_VERSION = "0.0.0"', 'ANAX_VERSION = "$APPVEYOR_REPO_TAG_NAME"' | Set-Content Anaximander2\Anaximander.exe.config
  - ps: (Get-Content Anaximander2\RollbarCrashReporter.exe.config) -replace 'ANAX_VERSION = "0.0.0"', 'ANAX_VERSION = "$APPVEYOR_REPO_TAG_NAME"' | Set-Content Anaximander2\RollbarCrashReporter.exe.config
  - ps: (Get-Content Anaximander2\Anaximander.exe.config) -replace 'COMPILED_BY = "?mono?"', 'COMPILED_BY = "VS2015"' | Set-Content Anaximander2\Anaximander.exe.config
  - ps: (Get-Content Anaximander2\RollbarCrashReporter.exe.config) -replace 'COMPILED_BY = "?mono?"', 'COMPILED_BY = "VS2015"' | Set-Content Anaximander2\RollbarCrashReporter.exe.config
  - nuget restore Source\Anaximander.sln

after_build:
  - rename bin Anaximander2
  - ps: (Get-Content Anaximander2\Anaximander.exe.config) -replace 'param name="Environment" value="development"', 'param name="Environment" value="production"' | Set-Content Anaximander2\Anaximander.exe.config
  - ps: (Get-Content Anaximander2\RollbarCrashReporter.exe.config) -replace 'param name="Environment" value="development"', 'param name="Environment" value="production"' | Set-Content Anaximander2\RollbarCrashReporter.exe.config

artifacts:
  - path: Anaximander2
    name: anaximander2-dotnet
    type: Zip

deploy:
  provider: GitHub
  auth_token:
    secure: "QUqhwTOVl7qBikVjSddIdfQ/mJAYlmSwsPPxTW8kSPJKALifV/E3UFycqJyf6USR"
  artifact: anaximander2-dotnet
  draft: true
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
