version: 2.0.{build}

image: Visual Studio 2015

nuget:
  account_feed: true
  project_feed: true

configuration: Release

build:
  parallel: true
  verbosity: minimal

before_build:
  - nuget restore Source\Anaximander.sln

after_build:
  - ps: (Get-Content bin\Anaximander.exe.config) -replace 'param name="Environment" value="development"', 'param name="Environment" value="production"' | Set-Content bin\Anaximander.exe.config
  - rename bin Anaximander2

artifacts:
  - path: Anaximander2
    name: anaximander2-dotnet
    type: Zip

deploy:
  provider: GitHub
  auth_token:
    secure: "QUqhwTOVl7qBikVjSddIdfQ/mJAYlmSwsPPxTW8kSPJKALifV/E3UFycqJyf6USR"
  artifact: anaximander2-dotnet
  draft: true
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
