language: csharp
solution: Source/Anaximander.sln
mono:
  - latest
  - 4.6.0
before_deploy:
  - sed -i 's/param name="Environment" value="development"/param name="Environment" value="production"/' bin/Anaximander.exe.config
